FROM golang:1.17.6-alpine AS build

WORKDIR /go/src/httpserver/

COPY httpserver/* /go/src/httpserver/
RUN go env -w GO111MODULE=auto && go build -o /bin/httpserver

FROM alpine:3.15.0
COPY --from=build /bin/httpserver /bin/
EXPOSE 80
ENTRYPOINT ["/bin/httpserver"]
